<header>
    <h1>@renderViewData("title");</h1>
</header>

<nav>
    <a href="#home">Home page</a>
    <a href="#about">About</a>
    <a href="#contact">Contact us</a>
</nav>

<div class="container">
    <h2>Welcome to website build from ProtonNet WebApiServer for __Server__ project.</h2>
    <p>This is a simple website with an interface similar to the default project of ASP.NET MVC 2. You can use it as a framework for your web projects.</p>
    
    </br>
    <p>Feel free to try out the following links:</p>
    <a href="/helloworld/hello">/helloworld/hello</a></br>
    <a href="/helloworld/ping">/helloworld/ping</a></br>
    <a href="/helloworld/getUTCDate">/helloworld/getUTCDate</a></br>
    <a href="/helloworld/debugApplication">/helloworld/debugApplication</a></br></br>
    <a href="/weather/getAllWeatherForecast">/weather/getAllWeatherForecast</a></br>
    <a href="/weather/getWeatherForecast?sumary=Sweltering">/weather/getWeatherForecast?sumary=Sweltering</a></br>
    <a href="/weather/getWeatherForecast/Warm">/weather/getWeatherForecast/Warm</a></br>
    <a href="/weather/getWeatherForecastMiddleware">/weather/getWeatherForecastMiddleware</a></br>
    </br>

    <div class="grid">
        <div class="grid-item">
            <h3>Feature 1</h3>
            <p>Content of feature 1. This is a brief piece of information.</p>
        </div>
        <div class="grid-item">
            <h3>Feature 2</h3>
            <p>Content of feature 2. This is a brief piece of information.</p>
        </div>
        <div class="grid-item">
            <h3>Feature 3</h3>
            <p>Content of feature 3. This is a brief piece of information.</p>
        </div>
    </div>
</div>

<footer>
    @renderPartial("footer");
</footer>
